# BOARD CONFIGS:
COLUMNS = 4
ROWS = 5

# ENVIRONMENT CONFIGS:
MAX_STEPS_WITHOUT_PROGRESS = 50
PREVIOUS_K_STEPS_IN_STATE = 1

MAX_STEPS_PER_EPISODE = 200

# AGENTS CONFIGS:
DISCOUNT_FACTOR_GAMMA = 0.99
LEARNING_RATE = 0.0001
BUFFER_CAPACITY = 100_000
REPLAY_WARMUP = 512
BATCH_SIZE = 256
SOFT_UPDATE_TAU = 0.001
BULK_UPDATE_EVERY_TRAIN_STEPS = 50

NUM_CHANNELS = 128
NUM_BLOCKS = 4

EPSILON_START = 1.0
EPSILON_END = 0.1

TRAIN_EPISODES = 1_000
EPSILON_DECAY_STEPS = 10_000

LOG_EVERY_EPISODE = 100
LOG_Q_EVERY_STEPS = 200

EVALUATE_GAMES = 100

CHECKPOINT_DIR_KAGGLE_DUMMY = "/kaggle/working/checkpoints"
CHECKPOINT_DIR_KAGGLE = "/checkpoints/pure_dqn_self_play"
CHECKPOINT_DIR_COLAB = "/content/drive/MyDrive/Grenight/checkpoints"

CHECKPOINT_EVERY_EPISODES = 5_000
