# BOARD CONFIGS:
COLUMNS = 4
ROWS = 5

# ENVIRONMENT CONFIGS:
MAX_ALLOWED_STEPS_WITHOUT_PAWN_MOVE_OR_CAPTURING = 50

# AGENTS CONFIGS:
MAX_STEPS_PER_EPISODE = 200
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY_EPISODES = 25_000
TRAIN_EPISODES = 18_000
CHECKPOINT_EVERY_EPISODES = 1_000
LOG_EVERY = 500
CHECKPOINT_DIR = "/kaggle/working/checkpoints"
