# BOARD CONFIGS:
COLUMNS = 4
ROWS = 5

# ENVIRONMENT CONFIGS:
MAX_STEPS_WITHOUT_PROGRESS = 50

# AGENTS CONFIGS:
EPSILON_START = 1.0
EPSILON_END = 0.15

MAX_STEPS_PER_EPISODE = 200

EPSILON_DECAY_STEPS_SELF_PLAY = 1_300_000
EPSILON_DECAY_STEPS_VS_RANDOM = 350_000
TRAIN_EPISODES = 50_000

LOG_EVERY_EPISODE = 1_000
LOG_Q_EVERY_STEPS = 2_000

EVALUATE_GAMES = 200

CHECKPOINT_DIR_KAGGLE = "/kaggle/working/checkpoints"
CHECKPOINT_DIR_COLAB = "/content/drive/MyDrive/Grenight/checkpoints"

CHECKPOINT_EVERY_EPISODES = 5_000
