# BOARD CONFIGS:
COLUMNS = 4
ROWS = 5

# ENVIRONMENT CONFIGS:
MAX_STEPS_WITHOUT_PROGRESS = 50

# AGENTS CONFIGS:
EPSILON_START = 1.0
EPSILON_END = 0.1

MAX_STEPS_PER_EPISODE = 200

EPSILON_DECAY_STEPS = 700_000
TRAIN_EPISODES = 25_000

LOG_EVERY_EPISODE = 1_000
LOG_Q_EVERY_STEPS = 2_000

EVALUATE_GAMES = 200

CHECKPOINT_DIR = "/kaggle/working/checkpoints"
CHECKPOINT_EVERY_EPISODES = 5_000
